services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  frontend:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src  
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
